# Generated by Django 5.1.4 on 2024-12-14 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_date_of_birth'),
        ('accounts', '0003_leader_balance'),
    ]

    operations = [
    ]
