# Generated by Django 4.2.16 on 2024-12-15 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customuser_date_of_birth"),
        ("accounts", "0004_merge_20241215_0202"),
    ]

    operations = []
