# Generated by Django 5.1.4 on 2024-12-14 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_customuser_date_of_birth'),
        ('investment_fund', '0004_alter_investmentfund_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('company_name', models.CharField(max_length=255)),
                ('investment_type', models.CharField(choices=[('Stocks', 'Stocks'), ('Real Estate', 'Real Estate')], max_length=100)),
                ('total_investment', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('approval_percentage', models.FloatField(default=0.0)),
                ('required_approval_percentage', models.FloatField(default=70.0)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('investment_duration', models.CharField(blank=True, max_length=255, null=True)),
                ('expected_return', models.FloatField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Completed', 'Completed')], default='Open', max_length=100)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='investment_opportunities/pdf/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='investment_opportunities/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_opportunities', to='investment_fund.investmentfund')),
            ],
        ),
        migrations.CreateModel(
            name='InvestorFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_invested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=100)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_investments', to='investment_fund.investmentfund')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='accounts.investor')),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='investments.investmentopportunity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'opportunity')},
            },
        ),
    ]
