# Generated by Django 4.2.16 on 2024-12-11 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_date_of_birth"),
        ("investment_fund", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("Deposit", "Deposit"),
                            ("Withdrawal", "Withdrawal"),
                            ("Profit", "Profit"),
                        ],
                        max_length=50,
                    ),
                ),
                ("amount", models.FloatField()),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="investmentfund",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="investmentfund",
            name="status",
            field=models.CharField(
                choices=[
                    ("Open", "Open"),
                    ("Closed", "Closed"),
                    ("Pending", "Pending"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="investmentfund",
            name="total_balance",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="wallet",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="investmentfund",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="investmentfund",
            name="leader",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="managed_fund",
                to="accounts.leader",
            ),
        ),
        migrations.AlterField(
            model_name="investmentfund",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(name="DepositWallet",),
        migrations.AddField(
            model_name="transactions",
            name="fund",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="investment_fund.investmentfund",
            ),
        ),
        migrations.AddField(
            model_name="transactions",
            name="wallet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="investment_fund.wallet",
            ),
        ),
    ]
