# Generated by Django 4.2.16 on 2024-12-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investment_fund", "0002_transactions_investmentfund_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="investmentfund",
            name="category",
            field=models.CharField(
                choices=[("Stocks", "Stocks"), ("Real Estate", "Real Estate")],
                default="Stocks",
                max_length=50,
            ),
        ),
    ]
