# Generated by Django 4.2.16 on 2024-12-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investment_fund", "0003_investmentfund_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investmentfund",
            name="is_active",
            field=models.CharField(
                choices=[("Active", "Active"), ("Inactive", "Inactive")],
                default="Inactive",
                max_length=50,
            ),
        ),
    ]
