# Generated by Django 4.2.16 on 2024-12-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investment_fund", "0004_alter_investmentfund_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="investmentfund",
            name="join_code",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
