# Generated by Django 4.2.16 on 2024-12-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investment_fund", "0006_alter_investmentfund_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investmentfund",
            name="is_active",
            field=models.CharField(
                choices=[("Active", "نشط"), ("Inactive", "غير نشط")],
                default="Inactive",
                max_length=50,
            ),
        ),
    ]
