# Generated by Django 4.2.16 on 2024-12-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investment_fund", "0007_alter_investmentfund_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="transaction_type",
            field=models.CharField(
                choices=[("Deposit", "ايداع"), ("Withdrawal", "سحب")],
                default="Deposit",
                max_length=50,
            ),
        ),
    ]
