# Generated by Django 4.2.16 on 2024-12-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investment_fund", "0008_alter_transactions_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="transaction_type",
            field=models.CharField(
                choices=[("Deposit", "ايداع"), ("Transfer", "تحويل")],
                default="Deposit",
                max_length=50,
            ),
        ),
    ]
