# Generated by Django 4.2.16 on 2024-12-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investment_fund", "0009_alter_transactions_transaction_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="investmentfund",
            name="profit_balance",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="wallet",
            name="profit_balance",
            field=models.FloatField(default=0.0),
        ),
    ]
