# Generated by Django 4.2.16 on 2024-12-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investment_fund", "0011_alter_investmentfund_join_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transactions", options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="transactions",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("Deposit", "إيداع"),
                    ("Transfer", "تحويل"),
                    ("Withdrawal", "سحب"),
                ],
                default="Deposit",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="profit_balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
